metadata:
  name: productcatalogservice
  namespace: hipster-shop
  uid: a93b8ce1-eff3-4f5a-aef9-7e1f3ee465e6
  resourceVersion: "174555"
  generation: 3
  creationTimestamp: "2026-03-10T17:21:40Z"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: productcatalogservice
      annotations:
        dt.owner: hipster-shop
        resource-optimization.dynatrace.com/enabled: "true"
        resource-optimization.dynatrace.com/github-branch: master
        resource-optimization.dynatrace.com/github-path: hipster-shop/productcatalogservice.yaml
        resource-optimization.dynatrace.com/github-repo: github.com/Observe-Resolve/resource-optimization
    spec:
      containers:
        - name: server
          image: "us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice:v0.10.4"
          ports: - name: grpc
              containerPort: 3550
              protocol: TCP
          env: - name: PORT
              value: "3550"
            - name: DISABLE_PROFILER
              value: "1"
          resources: limits:
              cpu: "400m"
              memory: "512Mi"
            requests:
              cpu: "610m"
              memory: "12Mi"
          livenessProbe: grpc:
              port: 3550
              service: ""
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe: grpc:
              port: 3550
              service: ""
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext: readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
      dnsPolicy: ClusterFirst
      securityContext:
{}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "25%"
      maxSurge: "25%"
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 3
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: True
      lastUpdateTime: "2026-03-11T14:13:25Z"
      lastTransitionTime: "2026-03-10T17:21:40Z"
      reason: NewReplicaSetAvailable
      message: "ReplicaSet \"productcatalogservice-5697bbdcd\" has successfully progressed."
    - type: Available
      status: True
      lastUpdateTime: "2026-03-11T14:16:49Z"
      lastTransitionTime: "2026-03-11T14:16:49Z"
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
