kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis-cart
  namespace: hipster-shop
  uid: c88b4cbe-ba1a-46d4-988d-45b5cb43e676
  resourceVersion: "174562"
  generation: 3
  creationTimestamp: "2026-03-10T17:21:41Z"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-cart
      annotations:
        dt.owner: hipster-shop
        resource-optimization.dynatrace.com/enabled: "true"
        resource-optimization.dynatrace.com/github-branch: master
        resource-optimization.dynatrace.com/github-path: hipster-shop/redis-cart.yaml
        resource-optimization.dynatrace.com/github-repo: github.com/Observe-Resolve/resource-optimization
    spec:
      volumes:
        - name: redis-data
          emptyDir: {}
      containers:
        - name: redis
          image: "redis:alpine"
          ports: - name: redis
              containerPort: 6379
              protocol: TCP
          resources: limits:
              cpu: "400m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts: - name: redis-data
              mountPath: /data
          livenessProbe: tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe: tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
      dnsPolicy: ClusterFirst
      securityContext:
{}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "25%"
      maxSurge: "25%"
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 3
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: True
      lastUpdateTime: "2026-03-11T14:13:25Z"
      lastTransitionTime: "2026-03-10T17:21:41Z"
      reason: NewReplicaSetAvailable
      message: "ReplicaSet \"redis-cart-65ccd59c75\" has successfully progressed."
    - type: Available
      status: True
      lastUpdateTime: "2026-03-11T14:16:49Z"
      lastTransitionTime: "2026-03-11T14:16:49Z"
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
